
title: PyO3 Tutorial
email: leo.ao404@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  A comprehensive tutorial for PyO3
baseurl: "/pyo3-tutorial"
url: "https://leo-ao-99.github.io" 

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

defaults:
  - scope:
      path: "tutorials/*"
    values:
      layout: "page"

##########################################################
# search part
search: false
##########################################################
# aux link
aux_links:
  "Github": 
    - "https://github.com/leo-ao-99/pyo3-tutorial"

aux_links_new_tab: true

##########################################################
# Navigation sidebar
nav_enabled: true
##########################################################

